-- Dropping tables if they already exist
drop table if exists arduino_forecast CASCADE 
drop table if exists clothes CASCADE 
drop table if exists photos CASCADE 
drop table if exists users CASCADE 
drop table if exists weather_forecasts CASCADE 
drop table if exists weather_forecast_daily_temperatures CASCADE 
drop table if exists weather_forecast_weather_alerts CASCADE 

--Creating the tables
create table arduino_forecast (id integer generated by default as identity, email varchar(255) not null, humidity double not null, temperature double not null, forecast_timestamp timestamp not null, primary key (id))
create table clothes (id integer generated by default as identity, clothing_material varchar(50) not null, clothing_name varchar(50) not null, clothing_occasion varchar(50) not null, rainproofness varchar(50) not null, clothing_type varchar(50) not null, wash_cycle boolean not null, clothing_weather_type varchar(50) not null, photo_id integer, user_id integer, primary key (id))
create table photos (id integer generated by default as identity, photo blob, photo_type varchar(255), clothing_item_id integer, primary key (id))
create table users (id integer generated by default as identity, appartment_number varchar(10), city varchar(85) not null, country_code varchar(2) not null, email varchar(320) not null, first_name varchar(50) not null, last_name varchar(50) not null, password varchar(50) not null, phone_number varchar(50) not null, street_name varchar(50) not null, street_number varchar(10) not null, washing_reset_day varchar(255) not null, zip_code varchar(10) not null, primary key (id))
create table weather_forecasts (id integer generated by default as identity, city varchar(255) not null, country_code varchar(255) not null, current_feels_like_temperature double not null, current_humidity integer not null, current_temperature double not null, wind_speed double not null, forecast_timestamp timestamp not null, highest_temperature double not null, latitude double not null, longtitude double not null, lowest_temperature double not null, rain_probability double not null, weather_description varchar(255) not null, weather_icon varchar(255) not null, primary key (id))
create table weather_forecast_daily_temperatures (weather_forecast_id integer not null, daily_temperatures double, daily_temperatures_key bigint not null, primary key (weather_forecast_id, daily_temperatures_key))
create table weather_forecast_weather_alerts (weather_forecast_id integer not null, weather_alerts varchar(255), weather_alerts_key bigint not null, primary key (weather_forecast_id, weather_alerts_key))

-- Adding relations to the tables
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table clothes add constraint FKt16ee0s9v77hqfafk7lfd8m20 foreign key (photo_id) references photos
alter table clothes add constraint FK9v7gut79d5gafwodlxbpv5y2x foreign key (user_id) references users
alter table photos add constraint FKiwquuhaghrc7wv078fwhwk901 foreign key (clothing_item_id) references clothes
alter table weather_forecast_daily_temperatures add constraint FKrw0rq80y330wb53wblql4hsde foreign key (weather_forecast_id) references weather_forecasts
alter table weather_forecast_weather_alerts add constraint FKguihqrlurpbp71ru6vo59uqv6 foreign key (weather_forecast_id) references weather_forecasts

-- Seeding the databases with testdata
insert into users (id, appartment_number, city, country_code, email, first_name, last_name, password, phone_number, street_name, street_number, washing_reset_day, zip_code) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
insert into clothes (id, clothing_material, clothing_name, clothing_occasion, photo_id, rainproofness, clothing_type, user_id, wash_cycle, clothing_weather_type) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?)
insert into clothes (id, clothing_material, clothing_name, clothing_occasion, photo_id, rainproofness, clothing_type, user_id, wash_cycle, clothing_weather_type) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?)
insert into clothes (id, clothing_material, clothing_name, clothing_occasion, photo_id, rainproofness, clothing_type, user_id, wash_cycle, clothing_weather_type) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?)
insert into clothes (id, clothing_material, clothing_name, clothing_occasion, photo_id, rainproofness, clothing_type, user_id, wash_cycle, clothing_weather_type) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?)
insert into clothes (id, clothing_material, clothing_name, clothing_occasion, photo_id, rainproofness, clothing_type, user_id, wash_cycle, clothing_weather_type) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?)
insert into clothes (id, clothing_material, clothing_name, clothing_occasion, photo_id, rainproofness, clothing_type, user_id, wash_cycle, clothing_weather_type) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?)
insert into clothes (id, clothing_material, clothing_name, clothing_occasion, photo_id, rainproofness, clothing_type, user_id, wash_cycle, clothing_weather_type) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?)
insert into clothes (id, clothing_material, clothing_name, clothing_occasion, photo_id, rainproofness, clothing_type, user_id, wash_cycle, clothing_weather_type) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?)
insert into clothes (id, clothing_material, clothing_name, clothing_occasion, photo_id, rainproofness, clothing_type, user_id, wash_cycle, clothing_weather_type) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?)
insert into clothes (id, clothing_material, clothing_name, clothing_occasion, photo_id, rainproofness, clothing_type, user_id, wash_cycle, clothing_weather_type) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?)
insert into clothes (id, clothing_material, clothing_name, clothing_occasion, photo_id, rainproofness, clothing_type, user_id, wash_cycle, clothing_weather_type) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?)
insert into clothes (id, clothing_material, clothing_name, clothing_occasion, photo_id, rainproofness, clothing_type, user_id, wash_cycle, clothing_weather_type) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?)
insert into clothes (id, clothing_material, clothing_name, clothing_occasion, photo_id, rainproofness, clothing_type, user_id, wash_cycle, clothing_weather_type) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?)
insert into clothes (id, clothing_material, clothing_name, clothing_occasion, photo_id, rainproofness, clothing_type, user_id, wash_cycle, clothing_weather_type) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?)

-- Dropping tables when the application shuts down
drop table if exists arduino_forecast CASCADE 
drop table if exists clothes CASCADE 
drop table if exists photos CASCADE 
drop table if exists users CASCADE 
drop table if exists weather_forecasts CASCADE 
drop table if exists weather_forecast_daily_temperatures CASCADE 
drop table if exists weather_forecast_weather_alerts CASCADE 